CREATE TABLE MEMBERS (
    IDX NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(30),
    AGE NUMBER(3),
    ADDR VARCHAR2(50),
    REGDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE MEMBERS_SEQ NOCACHE;

INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '홍길동1', 27, '서울', SYSDATE);
INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '홍길동2', 37, '대전', SYSDATE);
INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '홍길동3', 47, '대구', SYSDATE);
INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '홍길동4', 57, '부산', SYSDATE);
COMMIT;

SELECT * FROM MEMBERS ORDER BY NAME;